### ISSUE TITLE
缺少部分文件:simle:

### ISSUE THREAD

**Issue by DuTim** [Zora-LM/HGAN-DTI#1]
作者你好, 我发现现在的代码仓库不完整
1. 缺少模型等部分文件
![image](https://user-images.githubusercontent.com/50939742/196324651-313519d2-a7d5-4dd0-b9c7-dc79d90d23ef.png)

2. 缺少数据集
![image](https://user-images.githubusercontent.com/50939742/196324234-18485852-f32a-4ac3-8713-e431b7e8ba4b.png)

非常期待您的更新:rocket::rocket: :smile:

**Comment by Zora-LM** [comment]
你好，缺失文件已上传，谢谢。


| |
李梅
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月18日 10:54 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [Zora-LM/HGAN-DTI] 缺少部分文件:simle: (Issue #1) |

作者你好, 我发现现在的代码仓库不完整

缺少模型等部分文件


缺少数据集


非常期待您的更新🚀🚀😄

**Comment by DuTim** [comment]
🤔 非常感谢您的回复，但仍然缺少一个文件夹： kgembedUtils文件夹
![image](https://user-images.githubusercontent.com/50939742/196333865-0dfd144c-154d-44b2-9a93-47a74f35c2df.png)

**Comment by Zora-LM** [comment]
非常抱歉。
已上传。


| |
李梅
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月18日 12:14 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Zora-LM/HGAN-DTI] 缺少部分文件:simle: (Issue #1) |

🤔 非常感谢您的回复，但仍然缺少一个文件夹： kgembedUtils文件夹

**Comment by DuTim** [comment]
真的抱歉，不想打扰到您 : ,可是真的还是少一个文件: MAGNA_pkg/layernormalization.py 😂 
![image](https://user-images.githubusercontent.com/50939742/196358234-2258f380-87eb-4976-9134-db1c67fd859f.png)

**Comment by Zora-LM** [comment]
上传到MAGNA_KGE文件夹里了


| |
李梅
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月18日 15:01 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Zora-LM/HGAN-DTI] 缺少部分文件:simle: (Issue #1) |

真的抱歉，不想打扰到您 : ,可是真的还是少一个文件: MAGNA_pkg/layernormalization.py 😂
