### ISSUE TITLE
So many Bug

### ISSUE THREAD

**Issue by Leafaeolian** [Zora-LM/HGAN-DTI#2]
i cant python run_HGAN.py cause so many bug, plz fix it!
like:
ModuleNotFoundError: No module named 'MAGNA_pkg'
ModuleNotFoundError: No module named 'layernormalization'
dgl._ffi.base.DGLError: Cannot assign node feature "n_id" on device cuda:1 to a graph on device cpu. Call DGLGraph.to() to copy the graph to the same device.
TypeError: __init__() got an unexpected keyword argument 'args'
dgl._ffi.base.DGLError: DGLGraph.register_reduce_func is deprecated. Please directly call update_all with func as the argument.

**Comment by Zora-LM** [comment]
For the first problem, you just need to change the file name. The layernormalization is put in file MAGNA_KGE. For other problems, please fix them by yourself.
