### ISSUE TITLE
DataProcessing

### ISSUE THREAD

**Issue by Mr245** [Zora-LM/HGAN-DTI#3]
Hello Dear Author, We are very interested in your code and would like to reproduce the process. We noticed that the data_preprocess.py file seems to be incomplete, could you upload the complete code and briefly explain the data processing process. We would like to use your code to validate other datasets and look forward to hearing from you!

**Comment by Zora-LM** [comment]
What is the matter? The code is complete and we have tested it.

**Comment by Mr245** [comment]
We would like to know how you processed the DTI dataset of luo into files under data_luo\10_folds by way of data processing. Because we would like to perform relevant tests on other datasets.

**Comment by Zora-LM** [comment]
Randomly splitting known DTIs (positive samples) into 10 partitions. Randomly selecting the same number of unknown DTIs as that of known DTIs as negative samples, and randomly split negative samples into 10 partitions.

**Comment by Mr245** [comment]
Thank you very much. Can you provide the relevant code？

**Comment by wangmanjiang** [comment]
同问

**Comment by Zora-LM** [comment]
The code is uploaded.

**Comment by wangmanjiang** [comment]
啊大拿谢谢了
